version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.11
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
      labels:
        traefik.enable: "true"
        traefik.http.routers.api.entrypoints: "http"
        traefik.http.routers.api.rule: "Host(`*`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
        traefik.http.routers.api.service: "api@internal"
        traefik.http.services.api.loadbalancer.server.port: "8080"
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true
    driver: overlay