version: '3'

services:
  web:
    image: louislam/uptime-kuma:1
    deploy:
      labels:
        - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma`)"
        - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      replicas: 10
    networks:
      - "proxy"
networks:
  proxy:
    external:
      name: "traefik-net"